// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXJKeqFx1LkOI6m_onBegVxNXSqVF_RY',
    appId: '1:191678377015:web:130423ba54e1f725e123b2',
    messagingSenderId: '191678377015',
    projectId: 'todolistyoutubelearn',
    authDomain: 'todolistlearn-c2755.firebaseapp.com',
    storageBucket: 'todolistyoutubelearn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuuyNTF5NqDe6bjuS2Zih0LfiYraFRDR4',
    appId: '1:191678377015:android:506498d8771d751ce123b2',
    messagingSenderId: '191678377015',
    projectId: 'todolistyoutubelearn',
    storageBucket: 'todolistyoutubelearn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHpxs4rw-vUH-JmBGrVyN_CNK7kj5SQ9Y',
    appId: '1:191678377015:ios:927c02e94c60818fe123b2',
    messagingSenderId: '191678377015',
    projectId: 'todolistyoutubelearn',
    storageBucket: 'todolistyoutubelearn.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHpxs4rw-vUH-JmBGrVyN_CNK7kj5SQ9Y',
    appId: '1:191678377015:ios:927c02e94c60818fe123b2',
    messagingSenderId: '191678377015',
    projectId: 'todolistyoutubelearn',
    storageBucket: 'todolistyoutubelearn.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTXJKeqFx1LkOI6m_onBegVxNXSqVF_RY',
    appId: '1:191678377015:web:4738eec3b363c81ee123b2',
    messagingSenderId: '191678377015',
    projectId: 'todolistyoutubelearn',
    authDomain: 'todolistlearn-c2755.firebaseapp.com',
    storageBucket: 'todolistyoutubelearn.firebasestorage.app',
  );
}
