const arr = [
  {
    ChAc: "SCG",
    glAccount: 100,
    companyCode: 7720,
    longTest: "Conversion Control Account-GL",
  },
  {
    ChAc: "SCG",
    glAccount: 200,
    companyCode: 7720,
    longTest: "Conversion Control Account-AR",
  },
  {
    ChAc: "SCG",
    glAccount: 300,
    companyCode: 7720,
    longTest: "Conversion Control Account-AP",
  },
  {
    ChAc: "SCG",
    glAccount: 400,
    companyCode: 7720,
    longTest: "Conversion Control Account-AA",
  },
  {
    ChAc: "SCG",
    glAccount: 500,
    companyCode: 7720,
    longTest: "Conversion Control Account-IM",
  },
  {
    ChAc: "SCG",
    glAccount: 600,
    companyCode: 7720,
    longTest: "Conversion Control Account-P&L",
  },
  {
    ChAc: "SCG",
    glAccount: 100000,
    companyCode: 7720,
    longTest: "Petty cash",
  },
  {
    ChAc: "SCG",
    glAccount: 100001,
    companyCode: 7720,
    longTest: "Advance Payment Request-Dummy Account-Petty Cash",
  },
  {
    ChAc: "SCG",
    glAccount: 100008,
    companyCode: 7720,
    longTest: "Petty cash-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 100010,
    companyCode: 7720,
    longTest: "Cash on hand",
  },
  {
    ChAc: "SCG",
    glAccount: 100018,
    companyCode: 7720,
    longTest: "Cash on hand-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 100100,
    companyCode: 7720,
    longTest: "Cash in transit-credit card/Cash card",
  },
  {
    ChAc: "SCG",
    glAccount: 102000,
    companyCode: 7720,
    longTest: "Cash in bank-fixed deposit (not over 3 mths)",
  },
  {
    ChAc: "SCG",
    glAccount: 102008,
    companyCode: 7720,
    longTest: "Cash in bank-fixed deposit (not over 3 mths)-reval",
  },
  {
    ChAc: "SCG",
    glAccount: 102100,
    companyCode: 7720,
    longTest: "Debenture (not over 3 mths)-par value",
  },
  {
    ChAc: "SCG",
    glAccount: 102101,
    companyCode: 7720,
    longTest: "Debenture (not over 3 mths)-premium/discount value",
  },
  {
    ChAc: "SCG",
    glAccount: 102107,
    companyCode: 7720,
    longTest: "Debenture (not over 3 mths)-fair value adj",
  },
  {
    ChAc: "SCG",
    glAccount: 102108,
    companyCode: 7720,
    longTest: "Debenture (not over 3 mths)-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 102120,
    companyCode: 7720,
    longTest: "Bond (not over 3 mths)-par value",
  },
  {
    ChAc: "SCG",
    glAccount: 102121,
    companyCode: 7720,
    longTest: "Bond (not over 3 mths)-premium/discount value",
  },
  {
    ChAc: "SCG",
    glAccount: 102122,
    companyCode: 7720,
    longTest: "Inv.debt ins within 3 M-Amort cost-amort Premi/Dis",
  },
  {
    ChAc: "SCG",
    glAccount: 102126,
    companyCode: 7720,
    longTest: "Bond (not over 3 mths)-impair",
  },
  {
    ChAc: "SCG",
    glAccount: 102128,
    companyCode: 7720,
    longTest: "Bond (not over 3 mths)-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 103000,
    companyCode: 7720,
    longTest: "Cash in bank-fixed deposit (3-12mths)",
  },
  {
    ChAc: "SCG",
    glAccount: 103008,
    companyCode: 7720,
    longTest: "Cash in bank-fixed deposit (3-12mths)-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 103020,
    companyCode: 7720,
    longTest: "Bank dep. restricted/pledged (not over 12 m)",
  },
  {
    ChAc: "SCG",
    glAccount: 103028,
    companyCode: 7720,
    longTest: "Bank dep. restricted/pledged (not over 12 m)-reval",
  },
  {
    ChAc: "SCG",
    glAccount: 103300,
    companyCode: 7720,
    longTest: "Invest.in debt-maturity within 1 yrs-FVTPL",
  },
  {
    ChAc: "SCG",
    glAccount: 103301,
    companyCode: 7720,
    longTest: "Invest.in debt-within 1 yrs-FVTP-Prem/Disc",
  },
  {
    ChAc: "SCG",
    glAccount: 103307,
    companyCode: 7720,
    longTest: "Invest.in debt-within 1 yrs-FVTPL-FV Adjustment",
  },
  {
    ChAc: "SCG",
    glAccount: 103308,
    companyCode: 7720,
    longTest: "Invest.in debt-within 1 yrs-FVTPL-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 110100,
    companyCode: 7720,
    longTest: "Trade receivable-non related parties",
  },
  {
    ChAc: "SCG",
    glAccount: 110101,
    companyCode: 7720,
    longTest: "Suspense A/C -Trade AR claring-non related",
  },
  {
    ChAc: "SCG",
    glAccount: 110105,
    companyCode: 7720,
    longTest: "Trade receivable-non related parties-adjustment",
  },
  {
    ChAc: "SCG",
    glAccount: 110108,
    companyCode: 7720,
    longTest: "Trade receivable-non related parties-revaluation",
  },
  {
    ChAc: "SCG",
    glAccount: 110109,
    companyCode: 7720,
    longTest: "Trade receivable-non related parties-reaging",
  },
  {
    ChAc: "SCG",
    glAccount: 110110,
    companyCode: 7720,
    longTest: "Allowance for Doubtful-Ind.AR Trade-Non Rel.",
  },
  {
    ChAc: "SCG",
    glAccount: 110118,
    companyCode: 7720,
    longTest: "Allowance for Doubtful-Ind.AR Trade-Non Rel.-Rev.",
  },
  {
    ChAc: "SCG",
    glAccount: 110120,
    companyCode: 7720,
    longTest: "Allowance for Doubtful-Est.AR Trade-Non Rel.",
  },
  {
    ChAc: "SCG",
    glAccount: 110128,
    companyCode: 7720,
    longTest: "Allowance for Doubtful-Est.AR Trade-Non Rel.-Rev.",
  },
  {
    ChAc: "SCG",
    glAccount: 110140,
    companyCode: 7720,
    longTest: "Trade receivable-non related parties-bill",
  },
  {
    ChAc: "SCG",
    glAccount: 110160,
    companyCode: 7720,
    longTest: "Trade A/R-non related parties-post-dated cheque",
  },
  {
    ChAc: "SCG",
    glAccount: 110170,
    companyCode: 7720,
    longTest: "TradeA/R-non related party-return cheque from bank",
  },
  {
    ChAc: "SCG",
    glAccount: 110180,
    companyCode: 7720,
    longTest: "Trade A/R-non related parties-returned cheque A/R",
  },
  {
    ChAc: "SCG",
    glAccount: 110500,
    companyCode: 7720,
    longTest: "Trade receivable-related parties",
  },
  {
    ChAc: "SCG",
    glAccount: 110501,
    companyCode: 7720,
    longTest: "Suspense A/C -Trade AR claring-related party",
  },
  {
    ChAc: "SCG",
    glAccount: 110505,
    companyCode: 7720,
    longTest: "Trade receivable-related parties-adjustment",
  },
  {
    ChAc: "SCG",
    glAccount: 110507,
    companyCode: 7720,
    longTest: "Trade receivable-related party-mark to fair value",
  },
  {
    ChAc: "SCG",
    glAccount: 110508,
    companyCode: 7720,
    longTest: "Trade receivable-related parties-revaluation",
  },
  {
    ChAc: "SCG",
    glAccount: 110509,
    companyCode: 7720,
    longTest: "Trade receivable-related parties-reaging",
  },
  {
    ChAc: "SCG",
    glAccount: 110560,
    companyCode: 7720,
    longTest: "Trade receivable-related parties-post date cheque",
  },
  {
    ChAc: "SCG",
    glAccount: 110580,
    companyCode: 7720,
    longTest: "Trade receivable-related parties-return cheque A/R",
  },
  {
    ChAc: "SCG",
    glAccount: 110590,
    companyCode: 7720,
    longTest: "Accrued income for goods/services-related parties",
  },
  {
    ChAc: "SCG",
    glAccount: 110598,
    companyCode: 7720,
    longTest: "Accrued income for goods/service-related parti-rev",
  },
  {
    ChAc: "SCG",
    glAccount: 111100,
    companyCode: 7720,
    longTest: "S/T Revenue Dept. Receivable - VAT",
  },
  {
    ChAc: "SCG",
    glAccount: 111140,
    companyCode: 7720,
    longTest: "S/T Revenue Dept. Receivable - CIT",
  },
  {
    ChAc: "SCG",
    glAccount: 111149,
    companyCode: 7720,
    longTest: "S/T Revenue Dept. Receivable - CIT-Reaging",
  },
  {
    ChAc: "SCG",
    glAccount: 111200,
    companyCode: 7720,
    longTest: "Employee receivable-advance for shares",
  },
  {
    ChAc: "SCG",
    glAccount: 111210,
    companyCode: 7720,
    longTest: "Employee receivable-cash advance",
  },
  {
    ChAc: "SCG",
    glAccount: 111218,
    companyCode: 7720,
    longTest: "Employee receivable-cash advance-revaluation",
  },
  {
    ChAc: "SCG",
    glAccount: 111220,
    companyCode: 7720,
    longTest: "Employee receivable-advanc for scholarship student",
  },
  {
    ChAc: "SCG",
    glAccount: 111230,
    companyCode: 7720,
    longTest: "Employee receivable-allowance",
  },
  {
    ChAc: "SCG",
    glAccount: 111238,
    companyCode: 7720,
    longTest: "Employee receivable-allowance-revaluation",
  },
  {
    ChAc: "SCG",
    glAccount: 111240,
    companyCode: 7720,
    longTest: "Employee receivable-loan",
  },
  {
    ChAc: "SCG",
    glAccount: 111250,
    companyCode: 7720,
    longTest: "Employee receivable-cash reserve for payment",
  },
  {
    ChAc: "SCG",
    glAccount: 111258,
    companyCode: 7720,
    longTest: "Employee A/R-cash reserve for payment-revaluation",
  },
  {
    ChAc: "SCG",
    glAccount: 111260,
    companyCode: 7720,
    longTest: "Employee receivable-others",
  },
  {
    ChAc: "SCG",
    glAccount: 111268,
    companyCode: 7720,
    longTest: "Employee receivable-others-revaluation",
  },
  {
    ChAc: "SCG",
    glAccount: 111410,
    companyCode: 7720,
    longTest: "Subscription receivable",
  },
  {
    ChAc: "SCG",
    glAccount: 111420,
    companyCode: 7720,
    longTest: "Current Portion of Other long term receivable",
  },
  {
    ChAc: "SCG",
    glAccount: 111450,
    companyCode: 7720,
    longTest: "Other receivable",
  },
  {
    ChAc: "SCG",
    glAccount: 111458,
    companyCode: 7720,
    longTest: "Other receivable-revaluation",
  },
  {
    ChAc: "SCG",
    glAccount: 111460,
    companyCode: 7720,
    longTest: "Allowance for Doubtful-Ind.-Other AR",
  },
  {
    ChAc: "SCG",
    glAccount: 111468,
    companyCode: 7720,
    longTest: "Allowance for Doubtful-Ind.-Other AR-Rev.",
  },
  {
    ChAc: "SCG",
    glAccount: 111470,
    companyCode: 7720,
    longTest: "Allowance for Doubtful-Est.-Other AR",
  },
  {
    ChAc: "SCG",
    glAccount: 111478,
    companyCode: 7720,
    longTest: "Allowance for Doubtful-Est.-Other AR-Rev.",
  },
  {
    ChAc: "SCG",
    glAccount: 111480,
    companyCode: 7720,
    longTest: "Cheque Returned-Other Receivable",
  },
  {
    ChAc: "SCG",
    glAccount: 111500,
    companyCode: 7720,
    longTest: "Current account receivable-related parties",
  },
  {
    ChAc: "SCG",
    glAccount: 111501,
    companyCode: 7720,
    longTest: "Suspense A/C -Non Trade AR clearing-related par",
  },
  {
    ChAc: "SCG",
    glAccount: 111505,
    companyCode: 7720,
    longTest: "Current account receivable-relatd party-adjustment",
  },
  {
    ChAc: "SCG",
    glAccount: 111508,
    companyCode: 7720,
    longTest: "Current accnt receivable-related party-revaluation",
  },
  {
    ChAc: "SCG",
    glAccount: 111520,
    companyCode: 7720,
    longTest: "Receivable for incoming payment of related company",
  },
  {
    ChAc: "SCG",
    glAccount: 111530,
    companyCode: 7720,
    longTest: "Advance payment-Goods/Services-related parties",
  },
  {
    ChAc: "SCG",
    glAccount: 111580,
    companyCode: 7720,
    longTest: "Interest receivable-related parties",
  },
  {
    ChAc: "SCG",
    glAccount: 111588,
    companyCode: 7720,
    longTest: "Interest receivable-related parties-revaluation",
  },
  {
    ChAc: "SCG",
    glAccount: 111590,
    companyCode: 7720,
    longTest: "Accrued income for others-related parties",
  },
  {
    ChAc: "SCG",
    glAccount: 111598,
    companyCode: 7720,
    longTest: "Accrued income for others-related parties-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 111600,
    companyCode: 7720,
    longTest: "Receivable from sales of subsidiaries",
  },
  {
    ChAc: "SCG",
    glAccount: 111608,
    companyCode: 7720,
    longTest: "Receivable from sales of subsidiaries-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 111610,
    companyCode: 7720,
    longTest: "Receivable from sales of associate and JV",
  },
  {
    ChAc: "SCG",
    glAccount: 111618,
    companyCode: 7720,
    longTest: "Receivable from sales of associate and JV-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 111620,
    companyCode: 7720,
    longTest: "Receivable from sales of other investment",
  },
  {
    ChAc: "SCG",
    glAccount: 111628,
    companyCode: 7720,
    longTest: "Receivable from sales of other investment-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 112126,
    companyCode: 7720,
    longTest: "Allowance for impairment loss on loan non-related",
  },
  {
    ChAc: "SCG",
    glAccount: 112510,
    companyCode: 7720,
    longTest: "ST loan A/R-related party-promissory notes",
  },
  {
    ChAc: "SCG",
    glAccount: 112518,
    companyCode: 7720,
    longTest: "ST loan A/R-related party-promissory notes-revalue",
  },
  {
    ChAc: "SCG",
    glAccount: 112520,
    companyCode: 7720,
    longTest: "ST loan A/R-related party-loan agreement",
  },
  {
    ChAc: "SCG",
    glAccount: 113000,
    companyCode: 7720,
    longTest: "CP LT loan-finance leases receivable-non related",
  },
  {
    ChAc: "SCG",
    glAccount: 113100,
    companyCode: 7720,
    longTest: "CP-Invest. in Debt Inst.-Debentures (>1Y) (HTM)",
  },
];
const result = Object.values(
  arr.reduce((acc, item) => {
    if (!acc[item.longTest]) {
      acc[item.longTest] = {
        comp_code: item.companyCode,
        code: item.glAccount,
        name: item.longTest,
      };
    }
    return acc;
  }, {})
);

console.log(result);
