export const v_md_internal_order = [
  {
    code: "449010000002",
    name: "Computer for staff buy new",
    ResponsibleCCtr: "4490-60000",
    OrderStatus: "Release",
    Transcurrency: "USD",
    ObjCurrency: "USD",
    AssetClass: "5010-Computer and Accessary",
    Assignment: "1-IT",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "MR.WATANYU.B",
    BusinessArea: "",
    comp_code: "4490",
    WorkStart: "7/1/2023",
    EndofWork: "12/31/2023",
    ESGCategory: "",
    Statistical: "Yes",
    FiscalYear: "",
    Operatingcode: "2-During the period (Not annua",
  },
  {
    code: "449030000001",
    name: "SAP HR setup for SDRC",
    ResponsibleCCtr: "4490-60000",
    OrderStatus: "Release",
    Transcurrency: "USD",
    ObjCurrency: "USD",
    AssetClass: "6020-Software License",
    Assignment: "1-IT",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "WATANYU BOONKROB",
    BusinessArea: "DV00",
    comp_code: "4490",
    WorkStart: "6/30/2023",
    EndofWork: "12/31/2023",
    ESGCategory: "",
    Statistical: "No",
    FiscalYear: "",
    Operatingcode: "2-During the period (Not annua",
  },
  {
    code: "449030000004",
    name: "SDRC Agent Platform",
    ResponsibleCCtr: "4490-60000",
    OrderStatus: "Release",
    Transcurrency: "USD",
    ObjCurrency: "USD",
    AssetClass: "6020-Software License",
    Assignment: "1-IT",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "WATANYU BOONKROB",
    BusinessArea: "DV00",
    comp_code: "4490",
    WorkStart: "9/1/2023",
    EndofWork: "12/31/2023",
    ESGCategory: "",
    Statistical: "No",
    FiscalYear: "",
    Operatingcode: "2-During the period (Not annua",
  },
  {
    code: "449010000009",
    name: "Computer for New Staff 11 Set SRDC",
    ResponsibleCCtr: "4490-60000",
    OrderStatus: "Release",
    Transcurrency: "USD",
    ObjCurrency: "USD",
    AssetClass: "5010-Computer and Accessary",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "WATANYU BOONKROB",
    BusinessArea: "",
    comp_code: "4490",
    WorkStart: "12/19/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Statistical: "Yes",
    FiscalYear: "2024",
    Operatingcode: "2-During the period (Not annua",
  },
  {
    code: "449010000010",
    name: "Computer for replacement 11 set SRDC",
    ResponsibleCCtr: "4490-60000",
    OrderStatus: "Release",
    Transcurrency: "USD",
    ObjCurrency: "USD",
    AssetClass: "5010-Computer and Accessary",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "WATANYU BOONKROB",
    BusinessArea: "",
    comp_code: "4490",
    WorkStart: "12/19/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Statistical: "Yes",
    FiscalYear: "2024",
    Operatingcode: "2-During the period (Not annua",
  },
  {
    code: "449020000003",
    name: "Network Improvement PP",
    ResponsibleCCtr: "4490-60000",
    OrderStatus: "Release",
    Transcurrency: "USD",
    ObjCurrency: "USD",
    AssetClass: "5010-Computer and Accessary",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "MR.TONMAI",
    BusinessArea: "DV00",
    comp_code: "4490",
    WorkStart: "9/19/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Statistical: "No",
    FiscalYear: "2024",
    Operatingcode: "2-During the period (Not annua",
  },
  {
    code: "449020000004",
    name: "Customer Ralationship Management Softwar",
    ResponsibleCCtr: "4490-60000",
    OrderStatus: "Release",
    Transcurrency: "USD",
    ObjCurrency: "USD",
    AssetClass: "6020-Software License",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "WATANYU BOONKROB",
    BusinessArea: "DV00",
    comp_code: "4490",
    WorkStart: "12/19/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Statistical: "No",
    FiscalYear: "2024",
    Operatingcode: "2-During the period (Not annua",
  },
  {
    code: "449020000005",
    name: "Improve Techpert and Office SDRC",
    ResponsibleCCtr: "4490-90000",
    OrderStatus: "Release",
    Transcurrency: "USD",
    ObjCurrency: "USD",
    AssetClass: "2010-Other Structures",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "YAON PHEARUN",
    BusinessArea: "DV00",
    comp_code: "4490",
    WorkStart: "2/7/2025",
    EndofWork: "12/30/2025",
    ESGCategory: "01-Non-ESG",
    Statistical: "No",
    FiscalYear: "2025",
    Operatingcode: "2-During the period (Not annua",
  },
  {
    code: "449020000006",
    name: "Built-In Coffee Cabinet",
    ResponsibleCCtr: "4490-90000",
    OrderStatus: "Release",
    Transcurrency: "USD",
    ObjCurrency: "USD",
    AssetClass: "2010-Other Structures",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "HENG HORTECH",
    BusinessArea: "DV00",
    comp_code: "4490",
    WorkStart: "4/21/2025",
    EndofWork: "12/30/2025",
    ESGCategory: "01-Non-ESG",
    Statistical: "No",
    FiscalYear: "2025",
    Operatingcode: "2-During the period (Not annua",
  },

  {
    code: "772020000029",
    name: "Lightening Protection System at Quarry",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "MINING",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2021",
    EndofWork: "6/30/2021",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr.San Seiha",
    PlaceofInvestment: "",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000030",
    name: "Water System for Quarry Rehabilitation",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "MINING",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2021",
    EndofWork: "6/30/2021",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr.San Seiha",
    PlaceofInvestment: "",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000081",
    name: "Set Up Interior, Exterior of Bio.center",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "2000-Building",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "MR.SAN SEIHA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2022",
    EndofWork: "6/30/2022",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr.San Seiha",
    PlaceofInvestment: "",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000082",
    name: "Renovate Canteen & Kitchen Building",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "2000-Building",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "MR.SEN PHINA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "2/1/2022",
    EndofWork: "11/30/2022",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Tantikorn Wongsa",
    PlaceofInvestment: "",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000101",
    name: "Improve Security system @ Explosive",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "MR.HIM CHAKREY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2022",
    EndofWork: "4/30/2022",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr.San Seiha",
    PlaceofInvestment: "",
    ProcurementSource: "",
  },
  {
    code: "772020000108",
    name: "Repair & Install CCTV Camera at crushing",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "MR.MON HON",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2022",
    EndofWork: "12/31/2022",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr.San Seiha",
    PlaceofInvestment: "",
    ProcurementSource: "",
  },
  {
    code: "772020000111",
    name: "Renovation Cement Trucks Cement Parking",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "",
    Telephone: "MR.BUN RANTANA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2022",
    EndofWork: "12/31/2022",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Tantikorn Wongsa",
    PlaceofInvestment: "",
    ProcurementSource: "",
  },
  {
    code: "772020000185",
    name: "Overhaul MV inverter coal mill fan KCC1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "HENG LYNICH",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2023",
    EndofWork: "12/31/2023",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Taing Mengkuong",
    PlaceofInvestment: "",
    ProcurementSource: "",
  },
  {
    code: "772020000201",
    name: "ID card scanning to access gate (P2)",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "PHEN NARY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2023",
    EndofWork: "12/31/2023",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Tantikorn Wongsa",
    PlaceofInvestment: "",
    ProcurementSource: "",
  },
  {
    code: "772030000028",
    name: "Digital safe permit to work",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "6000-Intangible Asset",
    Assignment: "1-IT",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "MR.BUN RATANA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "8/1/2022",
    EndofWork: "12/31/2022",
    ESGCategory: "",
    Operatingcode: "3-Mid-year",
    OrderType: "QG03-7720 Intangible AUC",
    PersonResponsible: "Mr.Bun Ratana",
    PlaceofInvestment: "",
    ProcurementSource: "",
  },
  {
    code: "772030000035",
    name: "Smart Dispatching :Register& Queing syst",
    ResponsibleCCtr: "7720-72000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "6020-Software License",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "WATANYU BOONKROB",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2023",
    EndofWork: "12/31/2023",
    ESGCategory: "",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG03-7720 Intangible AUC",
    PersonResponsible: "Watanyu Boonkrob",
    PlaceofInvestment: "",
    ProcurementSource: "",
  },
  {
    code: "772010000100",
    name: "Compressive Machine 3,000KN RMC",
    ResponsibleCCtr: "7725-00904",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "HENG VANNAK RMC",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "11/25/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Heng Vannak RMC",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000101",
    name: "Organic Test RMC",
    ResponsibleCCtr: "7725-00904",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "HENG VANNAK RMC",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "11/25/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Heng Vannak RMC",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000102",
    name: "Coarse aggregate Sieve Shakers +Mesh RMC",
    ResponsibleCCtr: "7725-00904",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "HENG VANNAK RMC",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "11/25/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Heng Vannak RMC",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000103",
    name: "Fine aggregate sieve shakers +Mesh RMC",
    ResponsibleCCtr: "7725-00904",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "HENG VANNAK RMC",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "11/25/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Heng Vannak RMC",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000104",
    name: "Acme Penetrometer RMC",
    ResponsibleCCtr: "7725-00904",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "HENG VANNAK RMC",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "11/25/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Heng Vannak RMC",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000226",
    name: "Fire Pump and Fire hydrant System",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "MR. DUONG UDOM",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2024",
    EndofWork: "10/31/2024",
    ESGCategory: "08-Health & safety",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Duong Udom",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000227",
    name: "Renovate kitchen&Canteen at truck Parkin",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "2000-Building",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR. IN SERANN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2024",
    EndofWork: "11/30/2024",
    ESGCategory: "09-Social",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. In SerAnn",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000229",
    name: "Retrofit MCC set KCC1 sub Cooler KCC1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR. HENG LYNICH",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "5/1/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Heng Lynich",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000233",
    name: "Overhaul roller boss 05RM01-05RM201 K1&2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. IM LIN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Im Lin",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000234",
    name: "Overhaul rotor separator 05SE01 RM KCC1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. IM LIN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Im Lin",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000236",
    name: "Replace belt bucket Kiln feed 06BE02 K1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. KHAT VISAL",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "11/15/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Khat Visal",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000237",
    name: "Gearbox transpor at HRB cross cooler K1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. KHAT VISAL",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "11/15/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Khat Visal",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000238",
    name: "Gearbox grinding at HRB cross cooler K1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. KHAT VISAL",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "11/15/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Khat Visal",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000239",
    name: "Overhaul old gearbox of coal mill KCC1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. KHAT VISAL",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "11/15/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Khat Visal",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000240",
    name: "Upgrade air compressors 15aAC01,02 Packe",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MSS.AMMALY/MR.SAOTHO",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "11/15/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mss.Ammaly/Mr.Saoth",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000241",
    name: "Overhaul cylinder boom mobile crane 90T",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. HIN SOK HAY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "7/20/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Hin Sok Hay",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000243",
    name: "Improve gear motor of truck loading KCC1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. KHIENG LEM",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "8/20/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Khieng Lem",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000245",
    name: "Upgrade historian server & license K1&2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "6020-Software License",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "KAKADA CHHEUN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "8/20/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Kakada Chheun",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000249",
    name: "Minor overhaul turbine 23GE201",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. HIN SOK HAY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "8/20/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Hin Sok Hay",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000251",
    name: "Improvement gearmotor rotary 05RV206-207",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. IM LIN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "8/20/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Im Lin",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000252",
    name: "Replace new rail system stacker mix mate",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. IM LIN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "8/20/2024",
    EndofWork: "12/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. Im Lin",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000258",
    name: "Skim Coat machine and Equipment",
    ResponsibleCCtr: "7726-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "PRAMOTPI@SCG.COM",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "3/28/2024",
    EndofWork: "3/28/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr.Pramote",
    PlaceofInvestment: "",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000262",
    name: "Project modify Nozzle ring RM KCC2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "THYDA THEA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "6/12/2024",
    EndofWork: "2/28/2025",
    ESGCategory: "12-Low Carbon Product",
    Operatingcode: "3-Mid-year",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Thyda Thea",
    PlaceofInvestment: "O-Overseas",
    ProcurementSource: "2-Overseas",
  },
  {
    code: "772020000265",
    name: "Overhual Wheel Loader (PW04)",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Block",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "FOENG HINH CHUONG",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "8/1/2024",
    EndofWork: "8/31/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Foeng Hinh Chuong",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000270",
    name: "Convert Coal Mill 2 to be Biomass Dryer",
    ResponsibleCCtr: "7722-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "YOU KEY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/16/2024",
    EndofWork: "2/28/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "You Key",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000271",
    name: "Replace belt of bucket10cBE203 CM3 KCC2",
    ResponsibleCCtr: "7722-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "HENG LYNICH",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "You Key",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000272",
    name: "Minor Overhaul WHG1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "YOU KEY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "You Key",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000273",
    name: "Improve seal outlet Kiln KCC1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "YOU KEY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "You Key",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000274",
    name: "Auto clear snowman Kiln1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "YOU KEY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "You Key",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000275",
    name: "Modify existing blower fly ash KPP to CM",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "YOU KEY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "You Key",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000276",
    name: "Install rotor weight feeder feeding PIA",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "YOU KEY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "You Key",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000277",
    name: "Scale for bag cement",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "YOU KEY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "You Key",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000278",
    name: "Additonal Hydrant system to KPP area",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "YOU KEY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2024",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "You Key",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000279",
    name: "Hard to use Feeding project phase 1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "4-Project-Addition",
    Telephone: "MR.KHAT VISAL",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "11/23/2024",
    EndofWork: "4/30/2026",
    ESGCategory: "03-(Cancel) Energy efficiency",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr.You Key",
    PlaceofInvestment: "",
    ProcurementSource: "",
  },
  {
    code: "772020000280",
    name: "Installation Batching Plant Kampot2 RMC",
    ResponsibleCCtr: "7725-03100",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "2000-Building",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR.THIRACHET WIPASA",
    BusinessArea: "QGS0",
    comp_code: "7720",
    WorkStart: "12/20/2024",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr.Thirachet Wipasa",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772030000037",
    name: "Upgrade App/Improvement Running PR",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "6000-Intangible Asset",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "MR. CHHEM KANEY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2024",
    EndofWork: "12/31/2024",
    ESGCategory: "10-Governance",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG03-7720 Intangible AUC",
    PersonResponsible: "Mr. Chhem Kaney",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772030000038",
    name: "PM list & check sheet APP",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "6000-Intangible Asset",
    Assignment: "1-IT",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "MR. PEP VATANAK/KOEU",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "6/20/2024",
    EndofWork: "8/30/2024",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG03-7720 Intangible AUC",
    PersonResponsible: "Mr. Pep Vatanak/Koeu",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000112",
    name: "Computer for replace old XP window",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "5010-Computer and Accessary",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "HENG DARONG",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "2/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "HENG Darong",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000115",
    name: "Horbart Mixer",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR. SEU BUNCHOENG",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "5/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Mr. Seu Bunchoeng",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000116",
    name: "Digital Indicator",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR. SEU BUNCHOENG",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "6/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Mr. Seu Bunchoeng",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000117",
    name: "Thermometer 51/52 II",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR. SEU BUNCHOENG",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "6/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Mr. Seu Bunchoeng",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000118",
    name: "Printer for DN Cement and RM Slip",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR. HANG MARADY",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "2/1/2025",
    EndofWork: "8/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Mr. Hang Marady",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000121",
    name: "Furniture( Cabinet and Bed) at Town Hous",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "5000-Office Equip & Furniture",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR. HAM THETH",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "3/1/2025",
    EndofWork: "8/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Mr. Ham Theth",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000125",
    name: "Buy Iphone 16 pro 256GB for Dept Manager",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "5000-Office Equip & Furniture",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR.SEN PHINA",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "2/25/2025",
    EndofWork: "12/30/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Mr.Sen Phina",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000133",
    name: "CCTV XVR+HDD 8TB Camera at Cement Parkin",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "5000-Office Equip & Furniture",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR.HANG MARADY",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "4/18/2025",
    EndofWork: "5/30/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Mr.Hang Marady",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000134",
    name: "Computer for replacement at KCC Factory",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "5010-Computer and Accessary",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR.SIV CHORK",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "4/18/2025",
    EndofWork: "12/30/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Mr.Siv Chork",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000135",
    name: "TCMC Forklift Truck (load 3 ton)",
    ResponsibleCCtr: "7726-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "4010-Transportation Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "NIM PHANNITH",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "6/23/2025",
    EndofWork: "12/30/2025",
    ESGCategory: "15-Offsetting Strategy",
    Operatingcode: "2-During the period (Not annua",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Nim Phannith",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772010000136",
    name: "Pump Truck B11",
    ResponsibleCCtr: "7725-01301",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "4010-Transportation Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "KARIN ANONGKANATRAKU",
    BusinessArea: "",
    comp_code: "7720",
    WorkStart: "5/21/2025",
    EndofWork: "12/30/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG01-7720 Ready Made Asset (RMA)",
    PersonResponsible: "Karin Anongkanatraku",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000281",
    name: "Replace rotor disc CR2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "LUY VANNAK",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "11/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Luy Vannak",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000282",
    name: "Replace belt bucket RM KCC2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "IM LIN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2025",
    EndofWork: "12/31/2026",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Im Lin",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000283",
    name: "Upgrade chain of bucket 09BE01",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "EM CHIRAVUTH",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Em Chiravuth",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000284",
    name: "Overhaul separator CM3 KCC2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "EM CHIRAVUTH",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Em Chiravuth",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000285",
    name: "Overhaul gearbox roller press CM3",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "EM CHIRAVUTH",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "4/30/2025",
    EndofWork: "6/30/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Em Chiravuth",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000286",
    name: "Overhaul hydraulic motor CR KCC2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "LUY VANNAK",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Luy Vannak",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000287",
    name: "Replace pinion main gearbox CM3 KCC2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "EM CHIRAVUTH",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Em Chiravuth",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000288",
    name: "Upgrade seal roller RM KCC2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "IM LIN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Im Lin",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000289",
    name: "Electrical hydraulic pump",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "HIN SOKHAY",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "9/30/2025",
    EndofWork: "11/30/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Hin Sokhay",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000290",
    name: "Change wall EP RM chamber 4&5 KCC1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "IM LIN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "4/30/2025",
    EndofWork: "6/30/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Im Lin",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000291",
    name: "Change wall EP RM chamber 4&5 KCC2",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "IM LIN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "04-Air quality",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Im Lin",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000292",
    name: "Upgrade gearbox rotary valve05RV218-219",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "IM LIN",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Im Lin",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000293",
    name: "Change UPS at PLC panel CR KCC1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "CHHOEURN KAKADA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "10/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Chhoeurn Kakada",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000294",
    name: "Fire suppression system at KPP Sub",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "SEOURN RATHANAK",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "8/30/2025",
    EndofWork: "10/30/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Seourn Rathanak",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000295",
    name: "Bricking Machine, Model: DHJX/4.0-5.0",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "MR.YUON PISETH",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/15/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr.Yuon Piseth",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000296",
    name: "Motor vibrator 1.57kw (3phase,1500rpm)",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "1-Fixed Asset-Replacement",
    Telephone: "RIEM VANNAK",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/15/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Riem Vannak",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000297",
    name: "Impact wrench (Makita,TW0200) for SD M/C",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "RIEM VANNAK",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/15/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "03-(Cancel) Energy efficiency",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Riem Vannak",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000298",
    name: "Packing dump truck infront of MM1",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "1030-Land Improvement",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "THEA THYDA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/15/2025",
    EndofWork: "2/28/2025",
    ESGCategory: "04-Air quality",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Thea Thyda",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000299",
    name: "Project clean solar",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "UCH SAMNANG",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/15/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Uch Samnang",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000300",
    name: "Major Overhaul Excavator CAT-349D2 QE08",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "4010-Transportation Equipment",
    Assignment: "5-Project",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. SAN SEIHA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/31/2025",
    EndofWork: "5/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. San Seiha",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000301",
    name: "Overhaul Engine Dump Truck CAT-772E QT16",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "4010-Transportation Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. SAN SEIHA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "6/30/2025",
    EndofWork: "9/30/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. San Seiha",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000302",
    name: "Overhaul Engine DumpTruck CAT-772E QT17",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "4010-Transportation Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. SAN SEIHA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "9/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. San Seiha",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000303",
    name: "Overhaul Engine WheelLoaderCAT-988K QW05",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "4010-Transportation Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "MR. SAN SEIHA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "4/30/2025",
    EndofWork: "7/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Mr. San Seiha",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000304",
    name: "PM Part for furnace one set",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "KHOUN MAKARA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "4/30/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "KHOUN Makara",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000305",
    name: "PM Part for swing mill",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "KHOUN MAKARA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "4/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "KHOUN Makara",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000306",
    name: "PM Part for Manual Press",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "KHOUN MAKARA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "4/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "KHOUN Makara",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000307",
    name: "Obsolete Part XRD",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "KHOUN MAKARA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "2/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "KHOUN Makara",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000308",
    name: "PM PSD",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "5-MajorSparepart/Turnaround As",
    Telephone: "KHOUN MAKARA",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "5/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "KHOUN Makara",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000309",
    name: "Improve fiber optic cable struture",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "3000-Machinery & Equipment",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "TAING MENGKUONG",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Taing Mengkuong",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
  {
    code: "772020000310",
    name: "Improve room for internet at Townhouse",
    ResponsibleCCtr: "7721-01000",
    OrderStatus: "Release",
    TransCurrency: "USD",
    AssetClass: "2010-Other Structures",
    Assignment: "9-Other",
    BudgetStatus: "1-Original",
    CapitalExpenditureType: "2-Fixed Asset-Addition",
    Telephone: "TAING MENGKUONG",
    BusinessArea: "QG00",
    comp_code: "7720",
    WorkStart: "1/1/2025",
    EndofWork: "12/31/2025",
    ESGCategory: "01-Non-ESG",
    Operatingcode: "1-Annual Planning/Budgeting",
    OrderType: "QG02-7720 Asset Under Construction (AUC/CIP)",
    PersonResponsible: "Taing Mengkuong",
    PlaceofInvestment: "D-Domestic",
    ProcurementSource: "1-Domestic",
  },
];
