export const v_md_vendor = [
  {
    code: 31,
    name: "SCG DISTRIBUTION CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 31,
    name: "SCG DISTRIBUTION CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 32,
    name: "SCG DISTRIBUTION CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 32,
    name: "SCG DISTRIBUTION CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 32,
    name: "SCG DISTRIBUTION CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT01",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 112,
    name: "THE SIAM CEMENT PUBLIC COMPANY",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 112,
    name: "THE SIAM CEMENT PUBLIC COMPANY",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 112,
    name: "THE SIAM CEMENT PUBLIC COMPANY",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 122,
    name: "SCG CEMENT CO., LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 122,
    name: "SCG CEMENT CO., LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 131,
    name: "THE SIAM CEMENT (TA LUANG)",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "1 Moo.9 Patpong Rd.,Saraburi18270",
    payment_term: "NT30",
    currency: "MMK",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 132,
    name: "THE SIAM CEMENT (TA LUANG)",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "1 Moo.9 Patpong Rd.,Saraburi18270",
    payment_term: "NT30",
    currency: "MMK",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 141,
    name: "THE SIAM CEMENT (KAENG KHOI) CO.,LT",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "31/4 Moo.3Saraburi18110",
    payment_term: "NT00",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 141,
    name: "THE SIAM CEMENT (KAENG KHOI) CO.,LT",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "31/4 Moo.3Saraburi18110",
    payment_term: "NT00",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 142,
    name: "THE SIAM CEMENT (KAENG KHOI)",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "31/4 Moo.3Saraburi18110",
    payment_term: "NT00",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 142,
    name: "THE SIAM CEMENT (KAENG KHOI)",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "31/4 Moo.3Saraburi18110",
    payment_term: "NT00",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 151,
    name: "THE SIAM CEMENT (THUNG SONG)",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "55 Moo.6 Thungsong-Hauiyot Rd,Nakhon Si Thammarat80110",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 152,
    name: "THE SIAM CEMENT (THUNG SONG)",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "55 Moo.6 Thungsong-Hauiyot Rd.,Nakhon Si Thammarat80110",
    payment_term: "NT00",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 152,
    name: "THE SIAM CEMENT (THUNG SONG)",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "55 Moo.6 Thungsong-Hauiyot Rd.,Nakhon Si Thammarat80110",
    payment_term: "NT00",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 171,
    name: "ECO PLANT SERVICES CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "TL15",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 171,
    name: "ECO PLANT SERVICES CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "TL15",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 182,
    name: "SCG CEMENT-BUILDING MATERIALS",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 182,
    name: "SCG CEMENT-BUILDING MATERIALS",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 182,
    name: "SCG CEMENT-BUILDING MATERIALS",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 191,
    name: "THE SIAM CEMENT (LAMPANG) CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "279 Moo.5Lampang52120",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 192,
    name: "THE SIAM CEMENT (LAMPANG) CO., LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "279 Moo.5Lampang52120",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 192,
    name: "THE SIAM CEMENT (LAMPANG) CO., LTD.",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "279 Moo.5Lampang52120",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 301,
    name: "SCG ROOFING CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 301,
    name: "SCG ROOFING CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 302,
    name: "SCG ROOFING CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 302,
    name: "SCG ROOFING CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 312,
    name: "THE CONCRETE PRODUCTS AND",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1516 Pracharat 1 Rd.,Bangkok10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 312,
    name: "THE CONCRETE PRODUCTS AND",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1516 Pracharat 1 Rd.,Bangkok10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 312,
    name: "THE CONCRETE PRODUCTS AND",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "1516 Pracharat 1 Rd.,Bangkok10800",
    payment_term: "NT00",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 401,
    name: "NORITAKE SCG PLASTER CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "32 Moo.7 Nongplakradi Rd.,Saraburi18140",
    payment_term: "NT15",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 551,
    name: "THE SIAM REFRACTORY INDUSTRY",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 551,
    name: "THE SIAM REFRACTORY INDUSTRY",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 SIAM CEMENT ROAD,BANGKOK10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 591,
    name: "THE SIAM GYPSUM INDUSTRY",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "9 Pakin Bldg., 5th Fl.,Bangkok10400",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 591,
    name: "THE SIAM GYPSUM INDUSTRY",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "9 Pakin Bldg., 5th Fl.,Bangkok10400",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 651,
    name: "SCG CERAMICS PUBLIC COMPANY LIMITED",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "BRANCH DON MUANG, 36/11DONMUANG, BANGKOK10210",
    payment_term: "NT00",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 651,
    name: "SCG CERAMICS PUBLIC COMPANY LIMITED",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "BRANCH DON MUANG, 36/11DONMUANG, BANGKOK10210",
    payment_term: "NT00",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 652,
    name: "SCG CERAMICS PCL.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "BRANCH DON MUANG, 36/11DONMUANG, BANGKOK10210",
    payment_term: "TT00",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 652,
    name: "SCG CERAMICS PCL.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "BRANCH DON MUANG, 36/11DONMUANG, BANGKOK10210",
    payment_term: "TT00",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 812,
    name: "SIAM SANITARY WARE INDUSTRY CO.,LTD",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "36/11 Viphavadi Rangsit Rd.,Bangkok10210",
    payment_term: "NT00",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 812,
    name: "SIAM SANITARY WARE INDUSTRY CO.,LTD",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "36/11 Viphavadi Rangsit Rd.,Bangkok10210",
    payment_term: "NT00",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 821,
    name: "SCG International Corporation",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 SIAM CEMENT ROAD.,BANGKOK10800",
    payment_term: "NT00",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 821,
    name: "SCG International Corporation",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 SIAM CEMENT ROAD.,BANGKOK10800",
    payment_term: "NT00",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 1471,
    name: "CPAC CONSTRUCTION SOLUTION CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1516 Pracharat Sai 1 Rd.,Bangkok10800",
    payment_term: "NT00",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 1471,
    name: "CPAC CONSTRUCTION SOLUTION CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1516 Pracharat Sai 1 Rd.,Bangkok10800",
    payment_term: "NT00",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 1762,
    name: "SCGJWD ACADEMY CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "1 Siam Cement Rd.,Bangkok10800",
    payment_term: "NT30",
    currency: "MMK",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 1891,
    name: "BUU LONG INDUSTRY AND INVESTMENT",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "Binh Thach HamletDong Nai Province",
    payment_term: "NT00",
    currency: "USD",
    country: "VN",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 1891,
    name: "BUU LONG INDUSTRY AND INVESTMENT",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "Binh Thach HamletDong Nai Province",
    payment_term: "NT00",
    currency: "USD",
    country: "VN",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2201,
    name: "SCGJWD LOGISTICS",
    account_group: "KREP",
    purchase_org: "DV01",

    address:
      "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh120203",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2201,
    name: "SCGJWD LOGISTICS",
    account_group: "KREP",
    purchase_org: "QG01",

    address:
      "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh120203",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2201,
    name: "SCGJWD LOGISTICS",
    account_group: "KREP",
    purchase_org: "QG02",

    address:
      "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh120203",
    payment_term: "NT00",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2202,
    name: "SCG LOGISTICS MANAGEMENT (CAMBODIA)",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2202,
    name: "SCG LOGISTICS MANAGEMENT (CAMBODIA)",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2202,
    name: "SCG LOGISTICS MANAGEMENT (CAMBODIA)",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT00",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2541,
    name: "NAWAPLASTIC (CAMBODIA) CO., LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "PREY SPEU,SANGKAT CHOM CHAO,PHNOM PENH",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2541,
    name: "NAWAPLASTIC (CAMBODIA) CO., LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "PREY SPEU,SANGKAT CHOM CHAO,PHNOM PENH",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2931,
    name: "UNIFY SMART TECH JOINT STOCK",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "65 Hai Phong,Da Nang City, Viet Nam",
    payment_term: "NT30",
    currency: "VND",
    country: "VN",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 2931,
    name: "UNIFY SMART TECH JOINT STOCK",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "65 Hai Phong,Da Nang City, Viet Nam",
    payment_term: "NT30",
    currency: "VND",
    country: "VN",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 3231,
    name: "INNOVATE AI CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 3231,
    name: "INNOVATE AI CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 3232,
    name: "INNOVATE AI CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 3232,
    name: "INNOVATE AI CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 Siam Cement Road,Bangkok10800",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 3271,
    name: "SCG-BOONTHAVORN (CAMBODIA) CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "#6453 St.1003,Phum Bayab SangkatPhnom Penh120801",
    payment_term: "NT15",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 3271,
    name: "SCG-BOONTHAVORN (CAMBODIA) CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "#6453 St.1003,Phum Bayab SangkatPhnom Penh120801",
    payment_term: "NT15",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 3271,
    name: "SCG-BOONTHAVORN (CAMBODIA) CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "#6453 St.1003,Phum Bayab SangkatPhnom Penh120801",
    payment_term: "NT30",
    currency: "THB",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 3272,
    name: "SCG-BOONTHAVORN (CAMBODIA) CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "43 Maybank Tower, Norodom Blvd.Phnom Penh",
    payment_term: "NT15",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 3272,
    name: "SCG-BOONTHAVORN (CAMBODIA) CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "43 Maybank Tower, Norodom Blvd.Phnom Penh",
    payment_term: "NT15",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 4302,
    name: "SCG International Corporation",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "117-119 Ly Chinh Thang,Ho Chi Minh City",
    payment_term: "NT30",
    currency: "USD",
    country: "VN",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 4302,
    name: "SCG International Corporation",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "117-119 Ly Chinh Thang,Ho Chi Minh City",
    payment_term: "NT30",
    currency: "USD",
    country: "VN",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 4491,
    name: "SCG Distribution and Retail (Cambod",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "Maybank Tower, No.43,Preah NorodomPHNOM PENH120203",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 4491,
    name: "SCG Distribution and Retail (Cambod",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "Maybank Tower, No.43,Preah NorodomPHNOM PENH120203",
    payment_term: "NT30",
    currency: "THB",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 4492,
    name: "SCG Distribution and Retail (Cambod",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "Maybank Tower,No.43,Preah Norodom BKhan Daun Penh, Phnom Penh",
    payment_term: "NT45",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 4492,
    name: "SCG Distribution and Retail (Cambod",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "Maybank Tower,No.43,Preah Norodom BKhan Daun Penh, Phnom Penh",
    payment_term: "NT15",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 5411,
    name: "SCG International Hong Kong Limited",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "34/F Times Square Tower One,Hong Kong.",
    payment_term: "NT30",
    currency: "HKD",
    country: "HK",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 5411,
    name: "SCG International Hong Kong Limited",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "34/F Times Square Tower One,Hong Kong.",
    payment_term: "NT30",
    currency: "HKD",
    country: "HK",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 5561,
    name: "SCG International (Cambodia)",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "Maybank Tower 4th Floor, No.43,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 5561,
    name: "SCG International (Cambodia)",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "Maybank Tower 4th Floor, No.43,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 5561,
    name: "SCG International (Cambodia)",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "Maybank Tower 4th Floor, No.43,Khan Daun Penh, Phnom Penh",
    payment_term: "NT07",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 5562,
    name: "SCG International (Cambodia) Co., L",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT00",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 6212,
    name: "SCG EXPERIENCE CO., LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1444 Soi Ladprao 87  (Chandrasok)Bangkok10240",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 6212,
    name: "SCG EXPERIENCE CO., LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1444 Soi Ladprao 87  (Chandrasok)Bangkok10240",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 6471,
    name: "CPAC CAMBODIA CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 6471,
    name: "CPAC CAMBODIA CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 6471,
    name: "CPAC CAMBODIA CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 6472,
    name: "CPAC CAMBODIA CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "THB",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 6472,
    name: "CPAC CAMBODIA CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "THB",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 6472,
    name: "CPAC CAMBODIA CO.,LTD.",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "No.43 Maybank Tower, 4th-7th Fl.,Khan Daun Penh, Phnom Penh",
    payment_term: "NT30",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 7021,
    name: "SCG CONCRETE ROOF (CAMBODIA)",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "NATIONAL ROAD NO. 04, PHUM ANG KEO,PHNOM PENH120909",
    payment_term: "NT00",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 7021,
    name: "SCG CONCRETE ROOF (CAMBODIA)",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "NATIONAL ROAD NO. 04, PHUM ANG KEO,PHNOM PENH120909",
    payment_term: "NT00",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 7022,
    name: "SCG CONCRETE ROOF (CAMBODIA)",
    account_group: "KREP",
    purchase_org: "QG02",

    address: "National Road No.4, Phum Ang Keo,Khan Por Sen Chey, Phnom Penh",
    payment_term: "NT00",
    currency: "USD",
    country: "KH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 7041,
    name: "SCG LEGAL COUNSEL LIMITED",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 Siam Cement Rd.,Bangkok10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 7041,
    name: "SCG LEGAL COUNSEL LIMITED",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 Siam Cement Rd.,Bangkok10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 7042,
    name: "SCG LEGAL COUNSEL LIMITED",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "1 Siam Cement Road, Bangsue,Bangkok10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 7042,
    name: "SCG LEGAL COUNSEL LIMITED",
    account_group: "KREP",
    purchase_org: "QG01",

    address: "1 Siam Cement Road, Bangsue,Bangkok10800",
    payment_term: "NT30",
    currency: "USD",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
  {
    code: 7321,
    name: "IT ONE CO.,LTD.",
    account_group: "KREP",
    purchase_org: "DV01",

    address: "118/1 Tipco Tower, 21st -22nd Fl.,Bangkok10400",
    payment_term: "NT30",
    currency: "THB",
    country: "TH",
    tax_number: "188",
    city: "BangKok",
    bank_name: "Bangkok Bank",
    branch: "Main Branch",
  },
];
